chore(husky): update husky pre push hook to check branch name

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,4 +1,14 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
+# Branch prefix validation
+branch_name=$(git rev-parse --abbrev-ref HEAD)
+pattern="^(feat|chore|fix|release|docs|refactor|test)/"
+
+if [[ ! $branch_name =~ $pattern ]]; then
+  echo "Error: Branch name must start with one of 'feat/', 'chore/', 'fix/', 'release/', 'docs/', 'refactor/', 'test/'"
+  echo "Your branch name is: $branch_name"
+  exit 1
+fi
+
 npm run lint && npm run test:ci
